name: Feature Request
description: What feature would you like to see?
title: "[Feature Request]: your feature name here"
assignees:
  - vonschappler
labels:
  - enhancement
  - triage
body:
  - type: markdown
    attributes:
      value: |
        Please describe the feature you would like to see, with as much details as possible. Among the things that you can provide to help into detailing the feature we can mention:
        - Screenshots
        - Mockups
        - Links to similar features in other applications
        
  - type: dropdown
    id: type
    validations:
      required: true
    attributes:
      label: "What type of feature is this?"
      description: Select if this is a new feature to be added or a feature to be modified.
      options:
        - New feature to be added
        - Existent feature that can be improved
  
  - type: textarea
    id: feature-description
    validations:
      required: true
    attributes:
      label: "Please provide a detailed description of the feature you would like see in this application:"
      description: "A detailed description of the feature helps the developer into adding it properly."
      placeholder: |
        Use this box to provide all the information needed for us to understand what about the feature is and how it should work if added to the application.
  
  - type: textarea
    id: reasons
    validations:
      required: false
    attributes:
      label: "Why should we add this feature?"
      description: "Provide a reasonable explanation for why this feature should be added to this application."
      placeholder: Use this space to provide why this feature would be important to the application and how it would improve it, if added.

  - type: dropdown
    id: contact
    attributes:
      description: Let us know if you want to be contacted directly about the pregress of work into this.
      label: "Do you want to be contacted about this issue?"
      options:
        - "No"
        - "Yes"
      default: 0
    validations:
      required: true
  
  - type: input
    id: email
    attributes:
      label: "Email:"
      description: If you select "Yes" above, please provide your email address so that we can contact you about this feature request.
      placeholder: myemail@example.com
  
  - type: checkboxes
    id: consent
    attributes:
      label: 'Consentment:' 
      options:
        - label: By selecting "Yes" and providing my e-mail, I understand that the developer won't be using it for any other purposes than contacting me about this issue.
  
  - type: markdown
    attributes:
      value: |
        ---
        ## Terms:

  - type: checkboxes
    id: terms
    attributes:
      label: 'Agreement:' 
      options:
        - label: I agree that by submitting this report the informations listed here are suggestions that aim to improve the application.
          required: true
        - label: I understand that my request may take some time to be attended, and the proposal for improvements I suggested may not be accepted, hence not applied to the application.
          required: true