name: Bug Report
description: Is something not detailed enough or missimgin the help section? Tell us what using this form!
title: "[Bug Report]: your bug title here"
assignees:
  - vonschappler
labels:
  - bug
  - triage
body:
  - type: markdown
    attributes:
      value: |
        Please decribe with details the bug you encountered in this application, providing all necessary information to help us into reproducing and fixing the reported bug.
  
  - type: dropdown
    id: type
    validations:
      required: true
    attributes:
      label: "Operational System:"
      description: Select the option that fits the type of suggestion
      options:
        - Windows
        - Windows on a Virtual machine (on a Mac or Linux)
        
  - type: input
    id: os-version
    attributes:
      label: Operational System version
      description: Provide the version of your Operational System
      placeholder: Leave this if you are unsure about your OS version

  - type: dropdown
    id: type
    validations:
      required: true
    attributes:
      label: "Application version:"
      description: Select the option that fits the type of suggestion
      options:
        - Latest (current version)
        - "1.0.0"
      default: 0

  - type: textarea
    id: steps
    validations:
      required: true
    attributes:
      label: "Tell us how the error happend, providing as much details as possible:"
      description: "Providing the steps to reprocude the error helps us into working on the bug fix"
      placeholder: |
        Provide a detailed description of the steps that caused the error. Screenshots / screen recordings are useful also to add more context to your steps description. The template below helps you to provide a beter description of the steps necessary to reproduce the error.
  - type: markdown
    attributes:
      value: |
        Steps template:
        
        ```md
        - Open the application
        - Click on Download Updates button.
        - Download the update
        - The error happens after the update is downloaded
        ```

  - type: textarea
    id: stack
    attributes:
      render: shell
      label: "Error stack generated by the application (if that was the case):"
      description: "Copy and paste the error stack generated by the application, if existent"
      placeholder: |
        This field is specific ONLY for the full error stack generataed by the application IF the errors was caused by some sort of internal exceptions. If there are no error stacks, leave this blank.
  
  - type: markdown
    attributes:
      value: |
        ---
        ## Contact information:
  
  - type: dropdown
    id: contact
    attributes:
      description: Let us know if you want to be contacted directly about the pregress of work into this.
      label: "Do you want to be contacted about this issue?"
      options:
        - "No"
        - "Yes"
      default: 0
    validations:
      required: true
  
  - type: input
    id: email
    attributes:
      label: "Email:"
      description: If you select "Yes" above, please provide your email address so that we can contact you about this feature request
      placeholder: myemail@example.com
  
  - type: checkboxes
    id: consent
    attributes:
      label: 'Consentment:' 
      options:
        - label: By selecting "Yes" and providing my e-mail, I understand that the developer won't be using it for any other purposes than contacting me about this issue.
  
  - type: markdown
    attributes:
      value: |
        ---
        ## Terms:

  - type: checkboxes
    id: terms
    attributes:
      label: 'Agreement:' 
      options:
        - label: I agree that by submitting this report the informations listed here are suggestions that aim to improve the application.
          required: true
        - label: I understand that my request may take some time to be attended, and the proposal for improvements I suggested may not be accepted, hence not applied to the application.
          required: true