name: Feature Request
description: What feature would you like to see?
assignees:
  - vonschappler
labels:
  - enhancement
  - triage
body:
  - type: markdown
    attributes:
      value: Please describe the feature you would like to see.
  
  - type: checkboxes
    id: type
    attributes:
      label: "What type of feature is this?"
      description: Select if this is a new feature to be added or a feature to be modified.
      options:
        - label: New feature
          required: false
        - label: Feature to be modified
          required: false
  
  - type: textarea
    id: feature-description
    validations:
      required: true
    attributes:
      label: "Please provide a detailed description of the feature you would like see in this application:"
      description: "A detailed description of the feature helps the developer into adding it properly."
      placeholder: |
        Please describe the feature you would like to see. Screenshots, mockups and all relevant information such as links that display similar features in other applications are helpful to add context to the feature request.
  
  - type: textarea
    id: reasons
    validations:
      required: false
    attributes:
      label: "Why should we add this feature?"
      description: "Provide a reasonable explanation for why this feature should be added to this application."

  - type: checkboxes
    id: terms
    attributes:
      label: 'Agreement:' 
      options:
        - label: I understand that this feature request may not be attented if it does not meet the goals of the final product provided by thisapplication.
          required: true